version: '3.13'

services:
  # Servizio per il broker MQTT (Mosquitto)
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    restart: unless-stopped
    networks:
      - mqtt-network



  # Servizio per eseguire uno script Python specifico
  python-script-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simulator
    command: python /app/simulator.py
    volumes:
      - .:/app
    depends_on:
      - mqtt-broker
    networks:
      - mqtt-network

  python-script-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-script-2
    command: python /app/another_script.py
    volumes:
      - .:/app
    depends_on:
      - mqtt-broker
    networks:
      - mqtt-network

  # Altri container eventualmente necessari (ad esempio un database o un altro servizio)
  other-service:
    image: some-docker-image
    container_name: other-service
    restart: unless-stopped
    networks:
      - mqtt-network

networks:
  mqtt-network:
    driver: bridge
